# Generated by Django 4.2.2 on 2023-07-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
