# Generated by Django 4.2.2 on 2023-07-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0002_alter_candidate_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
    ]
