# Generated by Django 4.2.2 on 2023-07-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0002_alter_candidate_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Candidate/photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Candidate/Resume'),
        ),
    ]
