# Generated by Django 4.2.2 on 2023-07-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0004_alter_candidate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
