# Generated by Django 4.2.2 on 2023-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0005_alter_skill_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
