# Generated by Django 4.2.2 on 2023-07-11 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0007_candidate_git_hub_candidate_linked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='job_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('hired', 'hired')], default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
