# Generated by Django 4.2.3 on 2023-07-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
