# Generated by Django 4.2.3 on 2023-07-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0002_rename_department_sector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_posting',
            old_name='Sector',
            new_name='sector',
        ),
    ]
