# Generated by Django 4.2.3 on 2023-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0004_alter_experience_responsibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_posting',
            options={'ordering': ['-date_posted', '-date_closed']},
        ),
        migrations.RemoveField(
            model_name='job_posting',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='job_posting',
            name='job_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job_posting',
            name='salary_range_final',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_posting',
            name='salary_range_start',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=100000),
            preserve_default=False,
        ),
    ]
