# Generated by Django 4.2.3 on 2023-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0005_alter_job_posting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_posting',
            name='type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('seasonal ', 'seasonal'), ('contract', 'Contract')], max_length=30),
        ),
    ]
