# Generated by Django 4.2.3 on 2023-07-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0006_alter_job_posting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_posting',
            name='experience',
            field=models.FloatField(),
        ),
    ]
