# Generated by Django 4.2.3 on 2023-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0007_alter_job_posting_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_posting',
            name='salary_range_final',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='job_posting',
            name='salary_range_start',
            field=models.FloatField(),
        ),
    ]
