# Generated by Django 4.2.3 on 2023-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_System', '0008_alter_job_posting_salary_range_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_posting',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
