# Generated by Django 4.2.2 on 2023-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0003_candidate_photo_alter_candidate_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill',
            field=models.ManyToManyField(to='Recruitment_Management_System.skill'),
        ),
    ]
