# Generated by Django 4.2.2 on 2023-07-07 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0004_remove_skill_candidate_candidate_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
