# Generated by Django 4.2.2 on 2023-07-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment_Management_System', '0007_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recruitment_Management_System.candidate'),
        ),
    ]
