# Generated by Django 4.2.2 on 2023-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_blog_blog_categories_delete_mymodel_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_categories',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
