# Generated by Django 4.2.2 on 2023-06-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_alter_blog_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
