# Generated by Django 4.2.2 on 2023-07-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0010_alter_blog_categories_slug_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
