# Generated by Django 4.2.2 on 2023-07-07 06:15

from django.db import migrations
import fontawesome_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0015_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media',
            name='icon',
            field=fontawesome_5.fields.IconField(blank=True, max_length=60),
        ),
    ]
