# Generated by Django 4.2.2 on 2023-07-07 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_social_media_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
